## 1. (10 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.


In [2]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(np.intersect1d(a,b))

[2 4]


## 2. (10 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1 6 11
2 7 12
3 8 13
4 9 14
5 10 15


In [3]:
data = np.arange(1,16).reshape(3,5)
data.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## 3. (10 Points) The process of transforming a multidimensional array into a unidimensional array is referred to as
“flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of
values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15


In [4]:
for x in np.nditer(data):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


## 4. (15 Points) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column
becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and
the third column becomes the third dimension of the 3-D array.

In [5]:
d = data.reshape(5,1,3)
d

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]]])

## 5. (15 Points) Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2

In [6]:
e = d.reshape(5,3)
e

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## 6. (10 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [7]:
a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5])
result = np.setdiff1d(a, b)
print(result)

[ 1  7  8 15]


## 7. (30 Points)  This code will read the contents of the provided data file into a NumPy ndarray object. 
Execute the code within your Jupyter Notebook. If successful, the output of the type(nyc_water) function should be: numpy.ndarray
Using the nyc_water array you’ve created, answer the following questions using NumPy’s slicing, methods, and
functions


In [10]:
import pandas
import numpy as np
# supress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('Module6_Data.csv').to_numpy()
# verify you have an ndarray object
type(nyc_water)
# nyc_water

numpy.ndarray

### 7.1 What is the maximum yearly NYC consumption of water in millions of gallons per day?


In [17]:
# print(nyc_water.shape)
nyc_consum = nyc_water[:,2]
np.amax(nyc_consum)

1512.0

### 7.2 How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

In [26]:
print('begining:',nyc_water[0,0],'ending:',nyc_water[nyc_water.shape[0]-1,0],'Total years=',int(nyc_water[38,0]-nyc_water[0,0]+1),'years')

begining: 1979.0 ending: 2017.0 Total years= 39 years


### 7.3 What is the mean and the standard deviation of the per capita daily water consumption?


In [31]:
nyc_capita = nyc_water[:,3]
print('mean =', np.mean(nyc_capita), 'Standard Deviation = ', np.std(nyc_capita))

mean = 160.30769230769232 Standard Deviation =  31.51894330370624


### 7.4 What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [39]:
nyc_pop = nyc_consum/nyc_capita
pop_diff = np.diff(nyc_pop)*1000000
pop_diff

array([-28169.01408451,   5253.14046441,  48035.66453051,  68207.85171301,
        24829.57655371,  68965.51724138,  16988.41698842,  42474.96227192,
         1356.98849073,  -6220.51733969,   -107.95055864,  41703.36217168,
        58307.84356565,  79013.37792642,  65685.43188655,  34049.31612406,
        60916.13956335,  97537.69803398,  90322.58064516,  63027.29528536,
        71811.41439206,  -2580.64516129,  53900.70921986, -11988.94451397,
        42647.05882353, -13636.83771381,  27562.86266924,  32902.01282902,
         1946.47201946,  57723.57723577,  -9954.54836438, 119710.64592536,
        38856.41335752, 114952.42725189, -13943.8826378 , 110169.49152542,
        13255.10647544,  46332.21850613])